stages:
  - build

build:
  tags: ["shell"]
  stage: build
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
    - docker pull python:slim-buster
  script:
    - docker build -t $DOCKERHUB_USERNAME/zsync:latest .
    - docker push $DOCKERHUB_USERNAME/zsync:latest
  only:
    - main
