version: '3.8'

services:
  replication:
    image: 'zacharyr/replication:dev'
    container_name: 'replication'
    volumes:
      - ./keys/id_rsa:/home/replication/.ssh/id_rsa
      - ./args.json:/home/replication/args.json
      - ./test:/home/replication/local