name: Docker Build & Push

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker Hub Login
        uses: docker/login-action@master
        with:
          username: 'zacharyr'
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      -
        name: Build & Push
        id: docker_build
        uses: docker/build-push-action@master
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: zacharyr/zsync:latest
      - 
        name: Image Digest
        run: echo ${{ steps.docker_build.digest }}
