name: Docker Build & Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 */5 * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker Hub Login
        uses: docker/login-action@master
        with:
          username: 'zacharyr'
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      -
        name: Build & Push
        id: docker_build
        uses: docker/build-push-action@master
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: zacharyr/zsync:latest
  mattermost:
    runs-on: ubuntu-latest
    steps:
      -
        name: Compose Mattermost Message
        run : |
          echo "{\"text\":\"Docker image: `zsync:latest` built! :tada:\"}" > mattermost.json
      -
        uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
